version: '2'
services:
  chainmore:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=api.chainmore.fun
      - LETSENCRYPT_HOST=api.chainmore.fun
    volumes:
      - $HOME/chainmore:/workspace
